// Code generated by ogen, DO NOT EDIT.
package ogent

type CreatePersonRes interface {
	createPersonRes()
}

type DeletePersonRes interface {
	deletePersonRes()
}

type ListPersonRes interface {
	listPersonRes()
}

type ReadPersonRes interface {
	readPersonRes()
}

type UpdatePersonRes interface {
	updatePersonRes()
}
