// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreatePerson implements createPerson operation.
//
// Creates a new Person and persists it to storage.
//
// POST /people
func (UnimplementedHandler) CreatePerson(ctx context.Context, req *CreatePersonReq) (r CreatePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePerson implements deletePerson operation.
//
// Deletes the Person with the requested ID.
//
// DELETE /people/{id}
func (UnimplementedHandler) DeletePerson(ctx context.Context, params DeletePersonParams) (r DeletePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPerson implements listPerson operation.
//
// List Persons.
//
// GET /people
func (UnimplementedHandler) ListPerson(ctx context.Context, params ListPersonParams) (r ListPersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadPerson implements readPerson operation.
//
// Finds the Person with the requested ID and returns it.
//
// GET /people/{id}
func (UnimplementedHandler) ReadPerson(ctx context.Context, params ReadPersonParams) (r ReadPersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePerson implements updatePerson operation.
//
// Updates a Person and persists changes to storage.
//
// PATCH /people/{id}
func (UnimplementedHandler) UpdatePerson(ctx context.Context, req *UpdatePersonReq, params UpdatePersonParams) (r UpdatePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}
